name: Terraform Feature Branch - Security Scan and Plan

on:
  push:
    branches:
      - "feature/**"

permissions:
  contents: read

# =========================================================
# STAGE 1 - SECURITY SCAN
# =========================================================
jobs:
  security-scan:
    name: Stage 1 - Security Scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./azurerm_storage_account

    steps:

      # =========================================================
      # STEP 1 - Checkout Repository
      # =========================================================
      - name: Checkout Repository
        uses: actions/checkout@v4


      # =========================================================
      # STEP 2 - Setup Terraform
      # =========================================================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest


      # =========================================================
      # STEP 3 - Terraform Format Check
      # =========================================================
      - name: Terraform Format Check
        run: terraform fmt -recursive


      # =========================================================
      # STEP 4 - Setup TFLint
      # =========================================================
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5


      # =========================================================
      # STEP 5 - Run TFLint
      # =========================================================
      - name: Run TFLint
        run: |
          tflint --init
          tflint --recursive


      # =========================================================
      # STEP 6 - Run tfsec
      # =========================================================
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./azurerm_storage_account


      # =========================================================
      # STEP 7 - Run Checkov
      # =========================================================
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./azurerm_storage_account
          framework: terraform


      # =========================================================
      # STEP 8 - Setup Infracost
      # =========================================================
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}      # done


      # =========================================================
      # STEP 9 - Run Infracost
      # =========================================================
      - name: Run Infracost
        run: |
          infracost breakdown \
            --path=. \
            --format=table


  # =========================================================
  # STAGE 2 - TERRAFORM PLAN
  # =========================================================
  terraform-plan:
    name: Stage 2 - Terraform Plan
    runs-on: ubuntu-latest

    needs: security-scan

    defaults:
      run:
        working-directory: ./azurerm_storage_account

    steps:

      # =========================================================
      # STEP 1 - Checkout Repository
      # =========================================================
      - name: Checkout Repository
        uses: actions/checkout@v4


      # =========================================================
      # STEP 2 - Setup Terraform
      # =========================================================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest


      # =========================================================
      # STEP 3 - Azure Login Using Service Principal
      # =========================================================
      - name: Azure Login Using Service Principal
        run: |
          az login \
            --service-principal \
            --username "d9bc2374-158d-4c21-8c6a-ce6fa1b4a924" \
            --password "xVF8Q~z.lN6HVQgnOhX1UFSu7LG6u7mSEviWFaM3" \
            --tenant "91695fd6-371b-4c10-8dc9-21e31d347ad6"

          az account set \
            --subscription "b299f192-d573-4040-b542-2aff90a974b5"


      # =========================================================
      # STEP 4 - Verify Azure Subscription
      # =========================================================
      - name: Verify Azure Login
        run: az account show --output table


      # =========================================================
      # STEP 5 - Terraform Init
      # =========================================================
      - name: Terraform Init
        run: terraform init -input=false


      # =========================================================
      # STEP 6 - Terraform Validate
      # =========================================================
      - name: Terraform Validate
        run: terraform validate


      # =========================================================
      # STEP 7 - Terraform Plan
      # =========================================================
      - name: Terraform Plan
        run: terraform plan -input=false -no-color